// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/cube.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CubeService_CalculateCube_FullMethodName = "/cube.CubeService/CalculateCube"
)

// CubeServiceClient is the client API for CubeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CubeServiceClient interface {
	CalculateCube(ctx context.Context, in *CubeRequest, opts ...grpc.CallOption) (*CubeResponse, error)
}

type cubeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCubeServiceClient(cc grpc.ClientConnInterface) CubeServiceClient {
	return &cubeServiceClient{cc}
}

func (c *cubeServiceClient) CalculateCube(ctx context.Context, in *CubeRequest, opts ...grpc.CallOption) (*CubeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CubeResponse)
	err := c.cc.Invoke(ctx, CubeService_CalculateCube_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CubeServiceServer is the server API for CubeService service.
// All implementations must embed UnimplementedCubeServiceServer
// for forward compatibility.
type CubeServiceServer interface {
	CalculateCube(context.Context, *CubeRequest) (*CubeResponse, error)
	mustEmbedUnimplementedCubeServiceServer()
}

// UnimplementedCubeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCubeServiceServer struct{}

func (UnimplementedCubeServiceServer) CalculateCube(context.Context, *CubeRequest) (*CubeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateCube not implemented")
}
func (UnimplementedCubeServiceServer) mustEmbedUnimplementedCubeServiceServer() {}
func (UnimplementedCubeServiceServer) testEmbeddedByValue()                     {}

// UnsafeCubeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CubeServiceServer will
// result in compilation errors.
type UnsafeCubeServiceServer interface {
	mustEmbedUnimplementedCubeServiceServer()
}

func RegisterCubeServiceServer(s grpc.ServiceRegistrar, srv CubeServiceServer) {
	// If the following call pancis, it indicates UnimplementedCubeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CubeService_ServiceDesc, srv)
}

func _CubeService_CalculateCube_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CubeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeServiceServer).CalculateCube(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeService_CalculateCube_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeServiceServer).CalculateCube(ctx, req.(*CubeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CubeService_ServiceDesc is the grpc.ServiceDesc for CubeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CubeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cube.CubeService",
	HandlerType: (*CubeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateCube",
			Handler:    _CubeService_CalculateCube_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cube.proto",
}
