// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/cube.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CubeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CubeRequest) Reset() {
	*x = CubeRequest{}
	mi := &file_proto_cube_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CubeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CubeRequest) ProtoMessage() {}

func (x *CubeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cube_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CubeRequest.ProtoReflect.Descriptor instead.
func (*CubeRequest) Descriptor() ([]byte, []int) {
	return file_proto_cube_proto_rawDescGZIP(), []int{0}
}

func (x *CubeRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type CubeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CubeResponse) Reset() {
	*x = CubeResponse{}
	mi := &file_proto_cube_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CubeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CubeResponse) ProtoMessage() {}

func (x *CubeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cube_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CubeResponse.ProtoReflect.Descriptor instead.
func (*CubeResponse) Descriptor() ([]byte, []int) {
	return file_proto_cube_proto_rawDescGZIP(), []int{1}
}

func (x *CubeResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_cube_proto protoreflect.FileDescriptor

const file_proto_cube_proto_rawDesc = "" +
	"\n" +
	"\x10proto/cube.proto\x12\x04cube\"%\n" +
	"\vCubeRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\"&\n" +
	"\fCubeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result2E\n" +
	"\vCubeService\x126\n" +
	"\rCalculateCube\x12\x11.cube.CubeRequest\x1a\x12.cube.CubeResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_cube_proto_rawDescOnce sync.Once
	file_proto_cube_proto_rawDescData []byte
)

func file_proto_cube_proto_rawDescGZIP() []byte {
	file_proto_cube_proto_rawDescOnce.Do(func() {
		file_proto_cube_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cube_proto_rawDesc), len(file_proto_cube_proto_rawDesc)))
	})
	return file_proto_cube_proto_rawDescData
}

var file_proto_cube_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cube_proto_goTypes = []any{
	(*CubeRequest)(nil),  // 0: cube.CubeRequest
	(*CubeResponse)(nil), // 1: cube.CubeResponse
}
var file_proto_cube_proto_depIdxs = []int32{
	0, // 0: cube.CubeService.CalculateCube:input_type -> cube.CubeRequest
	1, // 1: cube.CubeService.CalculateCube:output_type -> cube.CubeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cube_proto_init() }
func file_proto_cube_proto_init() {
	if File_proto_cube_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cube_proto_rawDesc), len(file_proto_cube_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cube_proto_goTypes,
		DependencyIndexes: file_proto_cube_proto_depIdxs,
		MessageInfos:      file_proto_cube_proto_msgTypes,
	}.Build()
	File_proto_cube_proto = out.File
	file_proto_cube_proto_goTypes = nil
	file_proto_cube_proto_depIdxs = nil
}
